---
- hosts: flaskapp_nodes
  become: yes
  vars:
    - APP_NAME: flaskapp
    - REPOSITORY_URL: https://github.com/viktoriia-kravchuk/Hello-app-flask.git
  tasks:
    - name: "install os packages"
      yum:
        name: python3, python3-pip, git
    - name: "sync repo"
      git:
        repo: "{{REPOSITORY_URL}}"
        dest: "/opt/{{APP_NAME}}"
    - name: "create user"
      user:
        name: "{{APP_NAME}}"
    - name: "change permissions"
      file:
        owner: "{{APP_NAME}}"
        group: "{{APP_NAME}}"
        recurse: yes
        path: "/opt/{{APP_NAME}}"
    - name: "create venv"
      pip:
        requirements: "/opt/{{APP_NAME}}/requirements.txt"
        virtualenv: "/opt/{{APP_NAME}}/.venv"
        virtualenv_command: "python3 -m venv"
      become_user: "{{APP_NAME}}"
    - name: "put systemd cfg"
      template:
        src: files/flaskapp.service
        dest: "/etc/systemd/system/{{APP_NAME}}.service"
    - name: "start service"
      systemd:
        name: "{{APP_NAME}}"
        state: restarted
        daemon_reload: yes
- hosts: load_balancer
  become: yes
  vars:
    app_ips:
      - 172.31.11.15:8080
      - 172.32.10.30:8080
  tasks:
    - name: install epel
      yum:
        name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
        state: present
    - name: install nginx
      yum:
        name: nginx
        state: present
    - name: put nginx conf
      template:
        src: files/lb.conf
        dest: /etc/nginx/conf.d/flaskapp.conf
    - name: reload nginx
      systemd:
        name: nginx
        state: reloaded
